name: Build & Push Docker

on:
  push:
    branches: ["*"]

permissions:
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: |
          echo "SHA_TAG=sha-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "LATEST_TAG=latest" >> $GITHUB_OUTPUT
          echo "PREVIEW_TAG=${GITHUB_REF_NAME}-preview" >> $GITHUB_OUTPUT

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          tags: |
            "${{ github.repository }}:sha-${{ steps.vars.outputs.SHA_TAG }}"
            "${{ github.repository }}:latest"
            "${{ github.repository }}:${{ github.ref_name }}"
